table 'Enrollment by Year'
	isHidden
	lineageTag: 6f2eb3f6-f5b3-4ebf-b79e-73487be93417

	column InstituteID
		dataType: int64
		formatString: 0
		lineageTag: acab2a3a-5416-48c2-970f-08194ad5218b
		summarizeBy: none
		sourceColumn: InstituteID

		annotation SummarizationSetBy = Automatic

	column InstituteName
		dataType: string
		lineageTag: 1e92201a-c2c8-4ac3-9b43-0891dff56faa
		summarizeBy: none
		sourceColumn: InstituteName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Year
		dataType: int64
		formatString: 0
		lineageTag: d6bf0366-cd6c-4252-9fa4-d81635f33deb
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Enrollment
		dataType: int64
		formatString: 0
		lineageTag: 437e92fc-3862-4ab4-a7f4-6818ecdc209a
		summarizeBy: sum
		sourceColumn: Enrollment

		annotation SummarizationSetBy = Automatic

	partition EnrollmentByYear-c508c1f0-eb16-4d24-8f38-a6d24e7aca43 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(#"Report Data Source"[ExcelFileLocation]{0}), null, true),
				    EnrollmentByYear_Sheet = Source{[Item="EnrollmentByYear",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(EnrollmentByYear_Sheet,{{"Column1", type any}, {"Column2", type text}, {"Column3", type any}, {"Column4", type any}, {"Column5", type any}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type"),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Promoted Headers", {"InstituteID", "InstituteName"}, "Attribute", "Value"),
				    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Columns",{{"Attribute", "Year"}, {"Value", "EnrollmentTemp"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each [EnrollmentTemp] <> "-"),
				    #"Added Custom1" = Table.AddColumn(#"Filtered Rows", "Enrollment", each try Number.From([EnrollmentTemp]) otherwise 0),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom1",{"EnrollmentTemp"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"Enrollment", Int64.Type}, {"Year", Int64.Type}, {"InstituteID", Int64.Type}}),
				    #"Sorted Rows" = Table.Sort(#"Changed Type1",{{"InstituteName", Order.Ascending}})
				in
				    #"Sorted Rows"

	annotation PBI_ResultType = Table

